7. Post comment by article ID - Tested
SirPhoros/CTorrubia-News-Solo_Project-NC pull request #9
Opened 2023-05-10 10:01 UTC by SirPhoros

2023-05-10 10:25 UTC, johnhutcheon commented on __tests__/app.test.js
> +			})
We'd expect a 400 in this instance, as it's missing required fields (comment body in this case)

2023-05-10 10:27 UTC, johnhutcheon commented on __tests__/app.test.js
> +
Just a few more tests we need here please. Could we add the following?
- Status 201, ignores unnecessary properties (i.e. if you put something else apart from username and body in the post)
- Status 400, invalid ID, e.g. string of "not-an-id"
- Status 404, non existent ID, e.g. 0 or 9999

2023-05-10 10:28 UTC, johnhutcheon commented on models/articles.models.js
> +	}
We should also be checking that a username has been sent here as well

2023-05-10 10:29 UTC, johnhutcheon requested changes
Nice work! Just see my comments, a few changes required :)

2023-05-11 09:12 UTC, Geo-Beard reviewed
Looks OK overall - couple of small things, make those changes then feel free to merge and move on!

2023-05-11 09:12 UTC, Geo-Beard commented on __tests__/app.test.js
> +const { expect } = require('@jest/globals')
Looks like this is an auto-add, not sure that you need it.

2023-05-11 09:12 UTC, Geo-Beard commented on app.js
> +app.use((err, req, res, next) => {
You can have multiple if statements in one app.use - usually a good idea to keep PSQL errors together, but no problem leaving them separate.

2023-05-11 09:28 UTC, merged